config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :templates do
    resources :profiles, except: [:update, :edit]
  end

  resources :respondents

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  get '/profiles/complete', to: 'profiles#complete'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :respondent
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  acts_as_hashids
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_one :respondent, dependent: :destroy
  belongs_to :template

end

app/models/respondent.rb
class Respondent < ApplicationRecord
  belongs_to :profile
  has_one :answer, dependent: :destroy
  mount_uploader :image, MessageImageUploader
  enum firstperson: {watashi: 0, ore: 1, boku: 2,atashi: 3}
  attr_writer :year, :month, :day
  before_validation :set_birthday
  validates :name, presence: true
  @sentenceEnder = [["です。","かな。","だよ。","なんだ。","かな。","だよ!"],["だ！","だ。","だ。","だ。","だ!!","だ!"],["です。","かな。","だよ。","なんだ。","かな","だよ!"],["よ!","よ。","よ。","よ。","よ!!","よ!"]];

  attr_accessor :sentenceEnder

  def set_birthday
    self.birthday = [@year, @month,@day].join(",")
  end

  def self.return_sentence_ender(array_num, value_num)
    return @sentenceEnder[array_num][value_num]
  end
end

app/models/template.rb
class Template < ApplicationRecord
  belongs_to :user
  has_many :profiles, dependent: :destroy
  has_many :respondents, through: :profiles, dependent: :destroy
  validates :question1, presence: true
  validates :question2, presence: true
  validates :question3, presence: true
  validates :question4, presence: true
  validates :question5, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  has_many :templates, dependent: :destroy

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        email:    User.dummy_email(auth),
        image: auth.info.image,
        password: Devise.friendly_token[0, 20],
        name: auth.info.name
      )
    end

    if user.image != auth.info.image_tag
      user.update(image: auth.info.image)
    end

    user
  end

  private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_template, only:[:index, :new,:show]
  before_action :authenticate_user!, except:[:new,:create,:complete]
  protect_from_forgery :except => [:destroy]  
  
  def index

  end

  def new
    @respondent = Respondent.new();
  end

  def create
    template = Template.find(params[:template_id])
    @profile = Profile.new(template_id: template.id)
    if @profile.save
      @respondent = Respondent.new(respondent_param(@profile))
      if @respondent.save
        if Answer.create(answer_param(@respondent));
          respond_to do |format|
            format.json {@success="成功",@redirect=profiles_complete_path}
          end
        end
      else
        @profile.destroy;
        respond_to do |format|
          format.json {@success="失敗"}
        end
      end
    end
  end

  def complete

  end

  def show
    @profile = Profile.find(params[:id])
    @respondent = @profile.respondent;
    @answer = @respondent.answer;
  end

  def destroy
    @profile = Profile.find(params[:id])
    template = Template.find(params[:template_id])
    nickname = @profile.respondent.name
    if @profile.destroy
      redirect_to template_path(template), notice: nickname+'さんのプロフィールを削除しました'
    end
  end

  private
  def respondent_param(profile)
    params.permit(:name, :height, :bodyweight, :profession, :image,:year,:month, :day, :firstperson, :blood,:sign, :charmpoint, :personality, :skill, :hobby,:favoritefood,:dislikefood, :dream,:wish).merge(profile_id: profile.id)
  end

  def answer_param(respondent)
    params.permit(:answer1, :answer2, :answer3, :answer4, :answer5).merge(respondent_id: respondent.id)
  end

  def set_template
    @template = Template.includes(:user).find(params[:template_id]);
  end

end

app/controllers/templates_controller.rb
class TemplatesController < ApplicationController
  before_action :authenticate_user!
  protect_from_forgery :except => [:destroy]

  def index
    @templates = Template.where(user_id: current_user.id).page(params[:page]).per(3)
  end

  def new
    @template = Template.new()
  end

  def create
    @template = Template.new(template_params);
    if @template.save
      redirect_to templates_path, notice: 'テンプレートを作成しました'
    else
      flash.now[:notice] = "テンプレートの作成に失敗しました"
      render :new
    end
  end

  def show
    @template = Template.find(params[:id])
    @profiles = @template.profiles.includes(:respondent)
  end

  def destroy
    @template = Template.find(params[:id])

    if @template.destroy
      redirect_to templates_path, notice: 'テンプレートを削除しました'
    end
  end

  private
  def template_params
    params.permit(:question1, :question2, :question3, :question4, :question5).merge(user_id: current_user.id)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController


  def twitter
    callback_from :twitter
  end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/templates_helper.rb
module TemplatesHelper
end

app/views/home/index.html.erb
<div id="header" class="header">
  <div class="header-background">
      <div class="container">
        <div class="row">
          <div class="header-content">
            <div class="grid-example col s12 center-align header-title">
              <h1><%= image_tag '/images/logo.jpg'%></h1>
            </div>
            <div class="grid-example col s12 center-align"><span class= "top-h2">プロフィール手帳作成アプリ</span></div>
          </div>
        </div>
        <div class="center-align">
            <span class="top-h3">簡単3ステップでプロフィール帳が作れます</span>
          </div>
      </div>

    <div class="row">
        <div class="col s12 m4">
            <div class="icon-block">
                <h2 class="center light-blue-text"><i class="large material-icons">edit</i></h2>
                <span class=" text-size-middle">Create Template</span>
                <p class="center">答えて貰いたい5つの質問を考えてテンプレートを作成しましょう</p>
            </div>
        </div>
        <div class="col s12 m4">
            <div class="icon-block">
                <h2 class="center light-blue-text"><i class="large material-icons">group</i></h2>
                <span class="text-size-middle">URL Sharing</span>
                <p class="light">作ったテンプレートのURLを書いて欲しい人に共有しましょう</p>
            </div>
        </div>
        <div class="col s12 m4">
            <div class="icon-block">
                <h2 class="center light-blue-text"><i class="large material-icons">event_note</i></h2>
                <span class=" text-size-middle">Look Forward to Profile</span>
                <p class="light">あとはプロフィールを待つだけです</p>
            </div>
        </div>
    </div>
    <div class="center-align">
        <%= link_to templates_path do %>
        <button class="button1 center-align">早速使ってみる</button>
        <% end %>
    </div>
  </div>

</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prome</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="turbolinks-cache-control" content="no-cache">
     <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
     <script src="https://cdnjs.cloudflare.com/ajax/libs/pace/1.0.2/pace.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pace/1.0.2/themes/green/pace-theme-loading-bar.min.css" />
  </head>

  <body>
    <div class="wrap">
    <nav>
      <div class="nav-wrapper">
        <a href="/" class="brand-logo center">ProMe</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <% if user_signed_in? %>
            <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete%></li>
            <li><%= link_to "マイページへ", templates_path %></li>
          <% else%>
            <li><%= link_to "ログイン", user_twitter_omniauth_authorize_path%></li>
          <% end %>
        </ul>
      </div>
    </nav>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "flash flash__#{key}") %>
    <% end %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/profiles/complete.html.erb
<div class="container">
    <div class="complete_text"> <p>プロフィールを送信しました</p></div>
    <div class="complete_content">
        <div class="complete_content_br">あなたもあなただけのプロフィール帳を作成しませんか？</div>
        <div class="row">
            <div class="col s12 m4">
                <div class="icon-block">
                    <h2 class="center light-blue-text"><i class="large material-icons">edit</i></h2>
                    <span class=" text-size-middle">Create Template</span>
                    <p class="center">答えて貰いたい5つの質問を考えてテンプレートを作成しましょう</p>
                </div>
            </div>
            <div class="col s12 m4">
                <div class="icon-block">
                    <h2 class="center light-blue-text"><i class="large material-icons">group</i></h2>
                    <span class="text-size-middle">URL Sharing</span>
                    <p class="light">作ったテンプレートのURLを書いて欲しい人に共有しましょう</p>
                </div>
            </div>
            <div class="col s12 m4">
                <div class="icon-block">
                    <h2 class="center light-blue-text"><i class="large material-icons">event_note</i></h2>
                    <span class=" text-size-middle">Look Forward to Profile</span>
                    <p class="light">あとはプロフィールを待つだけです</p>
                </div>
            </div>
        </div>
        <div class="center-align">
            <%= link_to templates_path do %>
            <button class="button1 center-align">早速使ってみる</button>
            <% end %>
        </div>
    </div>
</div>

app/views/profiles/index.html.erb
<div class="container">
    <p>このURLを友達に共有してください</p>
    <div>
        <textarea id="bar"><%=new_template_profile_url(@template)%></textarea>
        <!-- Trigger -->
        <button class="clipboard-btn button4" data-clipboard-action="copy" data-clipboard-target="#bar">
            URLをコピーする
        </button>
        <a href="https://twitter.com/share" class="twitter-share-button" data-url=<%=new_template_profile_url(@template)%>
            data-text = "ProMe~プロフィール帳作成アプリ~ プロフィールを書いて下さい！"
            data-via =
            <%= current_user.name%>
            >ツイート</a>
        <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    </div>
</div>

app/views/profiles/new.html.erb
<div class="container">
  <div class="error">

  </div>
  <div class="row">
    <div class= "profile_content">
      <%= form_with url: template_profiles_path(@template), local: true, class: "col s12" do |f| %>
      <div class="container">

        <div class="profile_content_introduction">
            <div class="profile_content_introduction-text">
              <div class="text-form text-name">
                <label class="ef">
                  <div class="input-field">
                    <%= f.text_field :name, class: "input_text",maxlength: :"15"%>
                    <%= f.label :"お名前(15文字以内)" , for: :textarea2, class: "placeholder"%>
                  </div>
                </label>
              </div>
              <div class= "flex-height-bodyweight">
                <div class="text-form text-height-bodyweight">
                  <label class="ef">
                    <div class="input-field">
                      <%= f.text_field :height, maxlength: :"5"%>
                      <%= f.label :"身長" , for: :textarea2,  class: "placeholder"%>
                    </div>
                  </label>
                </div>

                <div class="text-form text-height-bodyweight">
                  <label class="ef">
                    <div class="input-field">
                      <%= f.text_field :bodyweight, maxlength: :"5"%>
                      <%= f.label :"体重" , for: :textarea2, class: "placeholder"%>
                    </div>
                  </label>
                </div>
              </div>
              <div class="text-form text-profession">
                  <label class="ef">
                    <div class="input-field">
                      <%= f.text_field :profession, class: "input_text",maxlength: :"15"%>
                      <%= f.label :"職業(15文字以内)" , for: :textarea2, class: "placeholder"%>
                    </div>
                  </label>
              </div>
            </div>
            <div class="field image">
              <%= f.label '似顔絵や写真など自分を表す写真を貼ってね' %>
              <div id="img_field" onClick="$('#upicon').click()" >
                  <i class="fas fa-image"></i><i class="fas fa-file-upload add"></i>
              </div>
              <%= f.file_field :image_before, class: "icon", style: "display:none;", id: "upicon"%>
            </div>


        </div>
          <div class="flex-row1">
              <%= f.select :firstperson, Respondent.firstpeople.keys.map {|k| [I18n.t("enums.respondent.firstperson.#{k}"), k]}, class: 'flex-row1-select'%>
              <span>は、</span>
              <div class="text-form text-year">
                <div class="input-field">
                  <%= f.text_field :year, maxlength: :"6", placeholder: "年"%>
                </div>
              </div>
              <span>年</span>
              <div class="text-form text-month">
                  <div class="input-field">
                    <%= f.text_field :month, maxlength: :"4", placeholder: "月"%>
                  </div>
              </div>
              <span>月</span>
              <div class="text-form text-day">
                  <div class="input-field">
                    <%= f.text_field :day, maxlength: :"4", placeholder: "日"%>
                  </div>
              </div>
              <span>日生まれの</span>
              <div class="text-form text-sign">
                <div class="input-field">
                    <%= f.text_field :sign, maxlength: :"4", placeholder: "星座"%>
                </div>
              </div>
              <span>座で、</span>
              <span>血液型は</span>
              <div class="text-form text-blood">
                <div class="input-field">
                    <%= f.text_field :blood, maxlength: :"4", placeholder: "血液型"%>
                </div>
              </div>
              <span class="sentence_ender1">です。</span>
          </div>

          <div class="flex-row2">
            <span>チャームポイントは</span>
            <div class="text-form text-charmpoint">
              <div class="input-field">
                <%= f.text_field :charmpoint, class: "input_text",maxlength: :"13"%>
                <%= f.label :"チャームポイント(13文字以内)" , for: :textarea2, class: "placeholder"%>
              </div>
            </div>
            <span>で、性格は</span>
            <div class="text-form text-personality">
              <div class="input-field">
                <%= f.text_field :personality, class: "input_text",maxlength: :"13"%>
                <%= f.label :"性格(13文字以内)" , for: :textarea2, class: "placeholder"%>
              </div>
            </div>
            <span class="sentence_ender2">かな。</span>
          </div>

          <div class="flex-row3">
            <span>特技は</span>
            <div class="text-form text-skill">
              <div class="input-field">
                <%= f.text_field :skill, class: "input_text",maxlength: :"13"%>
                <%= f.label :"特技(13文字以内)" , for: :textarea2, class: "placeholder"%>
              </div>
            </div>
            <span>で、趣味は</span>
            <div class="text-form text-hobby">
              <div class="input-field">
                <%= f.text_field :hobby, class: "input_text",maxlength: :"13"%>
                <%= f.label :"趣味(13文字以内)" , for: :textarea2, class: "placeholder"%>
              </div>
            </div>
            <span class="sentence_ender3">だよ。</span>
          </div>

          <div class="flex-row4">
            <span>好きな食べ物は</span>
            <div class="text-form text-favoritefood">
              <div class="input-field">
                <%= f.text_field :favoritefood, class: "input_text",maxlength: :"13"%>
                <%= f.label :"好きな食べ物(13文字以内)" , for: :textarea2, class: "placeholder"%>
              </div>
            </div>
            <span>で、嫌いな食べ物は</span>
            <div class="text-form text-dislikefood">
              <div class="input-field">
                <%= f.text_field :dislikefood, class: "input_text",maxlength: :"13"%>
                <%= f.label :"嫌いな食べ物(13文字以内)" , for: :textarea2, class: "placeholder"%>
              </div>
            </div>
            <span class="sentence_ender4">なんだ。</span>
          </div>

          <div class="flex-row5">
            <span>将来の夢は</span>
            <div class="text-form text-dream">
              <div class="input-field">
                <%= f.text_field :dream, class: "input_text",maxlength: :"13"%>
                <%= f.label :"将来の夢(13文字以内)" , for: :textarea2, class: "placeholder"%>
              </div>
            </div>
            <span class="sentence_ender5">かな。</span>
            <span>今一番欲しいものは</span>
            <div class="text-form text-wish">
              <div class="input-field">
                <%= f.text_field :wish, class: "input_text",maxlength: :"13"%>
                <%= f.label :"欲しい物(13文字以内)" , for: :textarea2, class: "placeholder"%>
              </div>
            </div>
            <span class="sentence_ender6">だよ!</span>
          </div>

          <div class=" profile_content_question">
          <ol class="list">
            <div class="flex-row6">
              <div class="text-form text-answer">
                <li><%= @template.question1 %></li>
                <div class="input-field">
                  <%= f.text_field :answer1, class: "input_text",maxlength: :"30"%>
                </div>
              </div>
            </div>

            <div class="flex-row7">
              <div class="text-form text-answer">
                <li><%= @template.question2 %></li>
                <div class="input-field">
                  <%= f.text_field :answer2, class: "input_text",maxlength: :"30"%>
                </div>
              </div>
            </div>

            <div class="flex-row8">
              <div class="text-form text-answer">
                <li><%= @template.question3 %></li>
                <div class="input-field">
                  <%= f.text_field :answer3, class: "input_text",maxlength: :"30"%>
                </div>
              </div>
            </div>

            <div class="flex-row9">
              <div class="text-form text-answer">
                <li><%= @template.question4 %></li>
                <div class="input-field">
                  <%= f.text_field :answer4, class: "input_text",maxlength: :"30"%>
                </div>
              </div>
            </div>

            <div class="flex-row10">
              <div class="text-form text-answer">
                <li><%= @template.question5 %></li>
                <div class="input-field">
                  <%= f.text_field :answer5, class: "input_text",maxlength: :"30"%>
                </div>
              </div>
            </div>
          </ol>
        </div>
            <div class="button3">
              作成する
            </div>

        </div>
      <% end %>
    <div class= "profile_content">
  </div>
</div>

  <div class="overlay" style="display:none;" >
    <div class="crop_modal"></div>
    <div class="close_btn"></div>
    <div class="select_icon_btn">決定</div>
  </div>

<aside class="is-modal">
    <div class="is-modal__inner">
        <div class="is-modal__body">
            <p>確認</p>
            <br />
            <div class="is-modal__body_font">
              <%= @template.user.name %>さんが作成したプロフィールです
            </div>
            <br />
            あなたのプロフィールを送ってあげましょう<br />相手に不愉快な思いをさせたり、迷惑をかける内容に注意しましょう

            <div class="profile-close-btn"><span></span></div>
        </div>
    </div>
</aside>

app/views/templates/_template.html.erb
      <div class="card Large">
          <div class="bgpattern ">
            <div class = "bgpattern_content">
              <br />
              <p class="zindex">質問1: <%= template.question1%><br />
              質問2: <%= template.question2%><br />
              質問3: <%= template.question3%><br />
              質問4: <%= template.question4%><br />
              質問5: <%= template.question5%><br />
              作成日: <%= template.created_at.in_time_zone('Tokyo').strftime("%Y/%m/%d %H:%M")%><br />
              プロフィール数: <%= template.profiles.length%></p>
            </div>
            <p>作成日: <%= template.created_at.strftime("%Y/%m/%d %H:%M")%></p>
            <p>プロフィール数: <%= template.profiles.length%></p>

        </div>
        <div class="card-action">
          <%= link_to "テンプレートURLを共有する", template_profiles_path(template)%>
          <%= link_to "書いてくれたプロフィールをみる", template_path(template)%>

          <%= icon 'fas', 'trash-alt', class: 'is-modal-icon', "data-id": template.to_param, "data-question1": template.question1, "data-question2": template.question2, "data-question3": template.question3,"data-question4": template.question4,"data-question5": template.question5%>

        </div>
      </div>

app/views/templates/index.html.erb
<div class="container">
    <div class="row">
        <div class="content">
            <div class="center-align user_name">
                <%= current_user.name%>
            </div>
            <div class="center-align">
                <div class="user_image">
                    <%= image_tag current_user.image, :size =>'160x240',class: "user_image_sicre"%>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="content mypage-box">
            <div class="grid-example col s12 center-align mypage-box-content">
                答えてもらうプロフィールのテンプレートを作成しましょう
            </div>
            <%= link_to new_template_path do %>
              <div class="grid-example col s12 center-align"><button class="button1">作成する</button></div>
            <% end %>
        </div>
    </div>
    <div class="row">
        <div class="container content">
             あなたが作ったテンプレート一覧
            <div class="template_box">
              <% if @templates.length > 0 %>
                <%= render @templates %>
              <% else %>
                <div class="template_box-no_img">
                  <%= icon 'fa', 'address-book'%>
                </div>
                <p class="template_box-no_content">まだプロフィールがありません</p>
              <% end %>
            </div>
            <div class="pagenate-box">
                <%= paginate @templates%>
            </div>
        </div>
    </div>
</div>
<aside class="is-modal">
    <div class="is-modal__inner">
        <div class="is-modal__body">
            <p>確認</p>
            <br />
            <div class="is-modal__body_gray">
            </div>
            <br />
            作成して貰ったプロフィールも削除されますが、<br />本当にこのテンプレートを削除してよろしいですか？
            <div class="cancel-btn">
                キャンセル
            </div>
            <div class="is-modal__body_delete">
                <%= button_to "削除する", "#", method: :delete , class: "delete-change cancel-btn", onfocus:"this.blur();"%>
            </div>
        </div>
    </div>
</aside>

app/views/templates/show.html.erb
<% if @profiles.length() != 0 %>
<div id="flipbook">
	<div class="hard"> プロフィール手帳</div>
	<div class="hard"></div>
    <% @profiles.each do |profile|%>
        <div class="template_content">
                
                    <%= form_with model: profile.respondent, local: true, class: "col s12" do |f| %>
                    <div class="template_content_introduction">
                        <div class="profile_content_introduction-text">
                            <div class="text-form text-name">
                                <label class="ef">
                                    <div class="input-field">
                                        <%= f.text_field :name, class: "input_text",maxlength: :"15",readonly: true%>
                                        <%= f.label :"お名前(15文字以内)" , for: :textarea2, class: "placeholder"%>
                                    </div>
                                </label>
                            </div>
                            <div class="flex-height-bodyweight">
                                <div class="text-form text-height-bodyweight">
                                    <label class="ef">
                                        <div class="input-field">
                                            <%= f.text_field :height, maxlength: :"5",placeholder: " ",readonly: true%>
                                            <%= f.label :"身長" , for: :textarea2,  class: "placeholder"%>
                                        </div>
                                    </label>
                                </div>
                                <div class="text-form text-height-bodyweight">
                                    <label class="ef">
                                        <div class="input-field">
                                            <%= f.text_field :bodyweight, maxlength: :"5",placeholder: " ",readonly: true%>
                                            <%= f.label :"体重" , for: :textarea2, class: "placeholder"%>
                                        </div>
                                    </label>
                                </div>
                            </div>
                            <div class="text-form text-profession">
                                <label class="ef">
                                    <div class="input-field">
                                        <%= f.text_field :profession, class: "input_text",maxlength: :"15", placeholder: " ",readonly: true%>
                                        <%= f.label :"職業(15文字以内)" , for: :textarea2, class: "placeholder"%>
                                    </div>
                                </label>
                            </div>
                        </div>
                        <div class="field image img_profile">
                            <%= f.label '似顔絵や写真など自分を表す写真を貼ってね' %>
                            <img src="<%= profile.respondent.image%>">
                        </div>
                    </div>
                    <div class="template_content_row1">
                        <div>
                            投稿日時:
                            <%= profile.created_at.in_time_zone('Tokyo').strftime("%Y/%m/%d %H:%M")%>
                        </div>
                        <div>
                            <%= link_to "詳細をみる",template_profile_path(@template,profile)%>
                            <%= icon 'fas', 'trash-alt', class: 'is-modal-profile-icon', "data-id": profile.to_param, "data-template-id": @template.to_param, "data-name": profile.respondent.name%>
                        </div>
                    </div>
                    <% end %>
                
        </div>
    <% end %>
    <div class="hard"></div>
</div>
<% else %>
<div class="container">
    まだプロフィールがありません
    URLを共有しましょう！
    <p>このURLを友達に共有してください</p>
    <div>
        <textarea id="bar"><%=new_template_profile_url(@template)%></textarea>
        <button class="clipboard-btn button4" data-clipboard-action="copy" data-clipboard-target="#bar">
            URLをコピーする
        </button>
        <a href="https://twitter.com/share" class="twitter-share-button" data-url=<%=new_template_profile_url(@template)%>
            data-text = "ProMe~プロフィール帳作成アプリ~ プロフィールを書いて下さい！"
            data-via =
            <%= current_user.name%>
            >ツイート</a>
        <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    </div>
</div>
<% end %>
<aside class="is-modal">
    <div class="is-modal__inner">
        <div class="is-modal__body">
            <p>確認</p>
            <br />
            <div class="is-modal__body_gray">
            </div>
            <br />
            <div class = "is-modal__body_content">
                本当にこのプロフィールを削除してよろしいですか？
            </div>
            <div class="cancel-btn">
                キャンセル
            </div>
            <div class="is-modal__body_delete">
                <%= button_to "削除する", "#", method: :delete , class: "delete-change cancel-btn", onfocus:"this.blur();"%>
            </div>
        </div>
    </div>
</aside>